CREATE PROCEDURE [dbo].[GetDatabaseRowVersion]
AS
BEGIN
	--SELECT CAST(@@DBTS AS BIGINT) AS CurrentRowVersion;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON

	SELECT DBTS = (CONVERT(BIGINT,MIN_ACTIVE_ROWVERSION())-1);
END;
GO
